name: Deploy Spring Boot to Podman

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        env:
          APP_CONFIG: ${{ secrets.APPLICATION_DEV_YML }}
        run: docker build --build-arg APP_CONFIG="$APP_CONFIG" -t catchmate-board:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Push Docker image
        run: docker push catchmate-board:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to RHEL9 server
        run: |
          ssh your-user@your-rhel9-server << 'EOF'
          podman pull catchmate-board:latest
          podman stop catchmate-board || true
          podman rm catchmate-board || true
          podman run -d --name catchmate-board -p 8080:8080 catchmate-board:latest
          EOF
